### ISSUE TITLE
Error ruta Fiji

### ISSUE THREAD

**Issue by jpincru** [danilexn/tronos#1]
Salta el mensaje de que no tengo FIJI instalado aunque lo tenga en la misma ruta de siempre, parece que si ejecuta el código correctamente (en este en concreto no detecta célula pero en otros las detecta igual que antes)

`jpincru@pop-os:~$ Tronos --source /home/jpincru/pelisdv/Sandra/TL1_sandra_AFA854_*_R3D.dv --workdir /home/jpincru/pelisdv/Sandra/results --project --track --threshold MaxEntropy --convert --minframes 120 --sizes 500 20000

  ______ ____   ____   _   __ ____  _____
 /_  __// __ \ / __ \ / | / // __ \/ ___/
  / /  / /_/ // / / //  |/ // / / /\__ \ 
 / /  / _, _// /_/ // /|  // /_/ /___/ /  
/_/  /_/ |_| \____//_/ |_/ \____//____/   
                                         
Welcome to TRONOS 0.2.0 by Daniel Leon-Perinan
[INFO] Parsing arguments...
[INFO] Z-Stacking will occur now
100%|██████████████████████████████████████████████████████| 107/107 [00:02<00:00, 37.54it/s]
[INFO] Saving projected image to .tif
[INFO] Generating and saving MaxEntropy threshold image
[TRONOS] [ERROR] Could not find FIJI installed in your Linux system
[TRONOS]->[FIJI] Passing data for file /home/jpincru/pelisdv/Sandra/results/TL1_sandra_AFA854_1_R3D_PRJ
[FIJI] Analyzing particles with default parameters
[TRONOS] [ERROR] Could not find FIJI installed in your Linux system
[FIJI]->[TRONOS] Result parsing and transformation
[TRONOS] Trajectory linking
[TRONOS] Filtering trajectories
[TRONOS] Track filter statistics
	Before: 1
	After: 0
[TRONOS] Trajectories were successfully saved to file /home/jpincru/pelisdv/Sandra/results/TL1_sandra_AFA854_1_R3D_PRJ_trajs.csv
[INFO] Completed processing of TL1_sandra_AFA854_1_R3D
`

**Comment by danilexn** [comment]
Gracias por reportar este error y por los detalles aportados; ha sido corregido en el commit https://github.com/danilexn/tronos/commit/86074fde0673e500835c9e9349e58267b57495ec
