### ISSUE TITLE
Error ruta de salida pdf

### ISSUE THREAD

**Issue by jpincru** [danilexn/tronos#3]
Al cambiar la ruta del output para el pdf da error, solo se genera correctamente en la carpeta del notebook si se deja por defecto.

# Calculate the global spectrum and plot

y.spec <- spectrum(y,log="yes",span=2,plot=FALSE,na.action=na.remove)

​

# Axis readjustment

spx <- y.spec$freq/sampling.time

spy <- 2*y.spec$spec

​

p.freq <- ggplot(data.frame(spy, spx), aes(y = spy, x = spx)) +

       geom_line() +

       theme_bw() +

       ggtitle(label = "Nuclear oscillations frequencies") +

       xlab("Frequency (Hz)") +

       ylab("Spectral density")

​

p.period <- ggplot(data.frame(spy, spx), aes((1/spx)/60, spy)) +

       geom_line() +

       ggtitle(label = "Nuclear oscillations periods") +

       theme_bw() +

       ylab("Spectral density") + 

       scale_x_continuous(trans = "log10") +

       xlab("Period (minutes)")

​

p.freq

p.period

​

pdf(paste0(analysis.name,"home/jpincru/pelisdv/pdfs/density/_spectral_density.pdf"))

p.period

p.freq

dev.off()

Error in pdf(paste0(analysis.name, "home/jpincru/pelisdv/pdfs/density/_spectral_density.pdf")): cannot open file 'AFA855_2_R3D_PRJ_trajshome/jpincru/pelisdv/pdfs/density/_spectral_density.pdf'
Traceback:

1. pdf(paste0(analysis.name, "home/jpincru/pelisdv/pdfs/density/_spectral_density.pdf"))

**Comment by danilexn** [comment]
Para indicar una ruta distinta de la ruta en la que se está ejecutando el notebook, hay que modificar la variable analysis.name, y no el contenido dentro de las llamadas a la función pdf. Como argumento de ruta, hay otra llamada a paste0 que concatena el nombre del análisis (analysis.name) con una cadena por defecto para cada tipo de plot, en el caso del ejemplo, "_spectral_density.pdf". 

Para el caso concreto en este issue, lo correcto será cambiar, en la celda _Loading data_:
`analysis.name <- basename(tools::file_path_sans_ext(file.route))`
por
`analysis.name <- paste0("/home/jpincru/pelisdv/pdfs/density/_spectral_density.pdf", basename(tools::file_path_sans_ext(file.route)))`
